### ISSUE TITLE
For whom this plugin is made for? Please include this explanation in the figma description

### ISSUE THREAD

**Issue by dmxt** [leadream/figma-icon-automation#1]
# For whom this plugin is made for?

_Obviously, this isn't the first thing that comes to mind for a developer, so I feel the need to address this._ 

### My background 
I'm a designer who only design interfaces and have experiences with building websites in HTML and SCSS. I only edited JS a few times, and it's the extent of my webdev knowledge.

### My first encounter
I first encountered this plugin through the official Figma repo:
 
![Figma_PEw9poLhbk](https://user-images.githubusercontent.com/3248782/69046463-fc57ab80-09c6-11ea-927f-9f98f85cb310.png)

I read the description, reread the description, and still couldn't understand what this plugin was for and how it would help me with my design tasks.

### An issue
I realized that other designers would have a worse time understanding of how to use this plugin, so I went on here to reiterate that Figma is used by mostly just designers who don't code nor know how to code, and they're not expected to understand how to use this plugin.

At the very least, it should be addressed for this plugin sitting in the designers' repository.

### A solution suggestion
My suggestion is to include at the top of the description explaining that this plugin is written for (React?) web developers and how it would help them with their tasks. 

It may show an indication that designers can exit the page right there before further wasting their time because it's probably not for them.

---

There may be a better solution but at least it could be better than the current state in the description section. Try reading it as if you're a designer and have zero knowledge in development:
![Figma_pICEsmrH2w](https://user-images.githubusercontent.com/3248782/69049813-ba326800-09ce-11ea-8e8a-737924bbd6e8.png)

**Comment by leadream** [comment]
@dmxt Sorry for confusing you. I'll improve the description to make it more designer friendly.

**Comment by leadream** [comment]
improved
https://www.figma.com/c/plugin/739395588962138807/figma-icon-automation

**Comment by dmxt** [comment]
It is a much more clear description now, good job!

Just a suggestion, the line "so you need a developmental knowledge to do that" type of line sounds harsh, it kicks a bit in self-esteem especially how targetted the line is :p Just leave it out like how my proposal:

![chrome_4NhFKYN0rb](https://user-images.githubusercontent.com/3248782/69301103-21286a80-0be3-11ea-9ace-5765dc71f33e.png)

It will feel much more relaxed and more neutral and not targetting or directing anything to anybody and at this point, it's already clear enough that it's for developers with the opening line and the prereq list. 😁

---

P.S. If you don't get the implication I was implying, then maybe you need design knowledge to understand this or perhaps get your designer friend to read it for you 

😉

**Comment by leadream** [comment]
@dmxt Thank you for your advice. I'm not very good at English so I don't know how to express something appropriately. I'll revise it, thanks.
