### ISSUE TITLE
请问这个插件能够支持多文件吗？

### ISSUE THREAD

**Issue by zhengpq** [leadream/figma-icon-automation#15]
你好，现在这个插件好像不支持多文件，比如我的文件 A 对应的是 github 上面的项目 A1，文件 B 对应的是github 项目 B1，但是目前这个插件好像不支持配置多个项目，想请问一下后续有考虑支持多项目配置吗？

**Comment by leadream** [comment]
@zhengpq 暂不支持，后续会增加这个功能。

**Comment by zhengpq** [comment]
@leadream ，好的，期待！
