### ISSUE TITLE
请问提示这个是什么原因。Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by guoshiyu** [leadream/figma-icon-automation#22]

**Comment by guoshiyu** [comment]
![image](https://user-images.githubusercontent.com/31948051/113836667-ac49d680-97bf-11eb-8784-3605f48046b2.png)

**Comment by hallee9000** [comment]
icon 是别人的 NPM 库，你要自己建一个库，不能和别人的同名。
https://juejin.cn/post/6844904030976606216#heading-25
