### ISSUE TITLE
Support for private repositories

### ISSUE THREAD

**Issue by danithecake** [leadream/figma-icon-automation#3]
Hi, I'm trying to integrate icons from Figma with my private Github repo and I have problems with it.
I've carefully followed all the steps from readme but I've receive errors in browser console when I'm trying to push icons to the repo. It looks like a plugin is unable to find `package.json` in my repo and after looking at a plugin source code I found its because unauthorised request is used here
```
export const getContent = (filePath, githubData) => {
  return fetch(`${base}/repos/${githubData.owner}/${githubData.name}/contents/${filePath}`, {
    headers: {
      'content-type': 'application/json'
    }
  })
  .then(response => response.json())
  .then(res => (
    res.sha ?
    {sha: res.sha, contents: JSON.parse(window.atob(res.content))} :
    {}
  ))
}
```

Could you provide support for private repositories?

**Comment by leadream** [comment]
@danithecake thanks for pointing, just ignored private repo. I'll fix it later.

**Comment by danithecake** [comment]
@leadream thx for the response. I've created a PR #4 with changes that I think will be enough for working with private repos.
*Tested with my private repo>

**Comment by leadream** [comment]
@danithecake sorry, I've been busy these days. Just tested and it works well. I've published it to Figma plugin community. you can try it now! Thanks for your PR.

**Comment by danithecake** [comment]
@leadream no problem. Thanks for the great plugin!
