### ISSUE TITLE
No icon files inside the pull-requests

### ISSUE THREAD

**Issue by XmlmXmlmX** [leadream/figma-icon-automation#33]
There are no icon files inside the pull-requests. Not sure what's wrong.

![image](https://user-images.githubusercontent.com/677165/169485527-98f1dbf0-ba38-40b0-8a3f-61fd07abe195.png)

![image](https://user-images.githubusercontent.com/677165/169485883-01e4b867-7f8a-481e-9fee-78ef688da164.png)

Also the github page doesn't work:

![image](https://user-images.githubusercontent.com/677165/169486410-96a337f3-7678-4692-944b-44855108e0c7.png)

There are some missing resources:

```
Failed to load resource: the server responded with a status of 404 () chunk-vendors.7ac5b11d.js:1
Failed to load resource: the server responded with a status of 404 () app.6c473867.css:1
Failed to load resource: the server responded with a status of 404 () chunk-vendors.44cae7ab.css:1
Failed to load resource: the server responded with a status of 404 () app.604bf28a.js:1
Failed to load resource: the server responded with a status of 404 () /juuust-vue-icon/favicon.ico:1

```

**Comment by hallee9000** [comment]
Hi @XmlmXmlmX, that's the expected result. This plugin only changes the version in `package.json`, and won't upload icon data to your repo. I guess some path issue causes the error. Not sure what's wrong with your workflow based on this information.

ps: I'm working on an improved version of this plugin.

**Comment by XmlmXmlmX** [comment]
Ok I see, now it's working. Thanks
