### ISSUE TITLE
[error] You have to provide a GITHUB_TOKEN or GITHUB_PAT

### ISSUE THREAD

**Issue by jiantaolovebingbing** [leadream/figma-icon-automation#6]
actions error: You have to provide a GITHUB_TOKEN or GITHUB_PATH
As i know, GITHUB_TOKEN only use in figma push action
thanks
<img width="771" alt="figma2" src="https://user-images.githubusercontent.com/33253363/86507749-5baae480-be0d-11ea-97cd-272445842154.png">

<img width="852" alt="figma" src="https://user-images.githubusercontent.com/33253363/86507660-92ccc600-be0c-11ea-9d06-2764a26e43f6.png">

**Comment by leadream** [comment]
@jiantaolovebingbing In Vue sample, the action need GitHub token for GitHub Pages deployment.
https://github.com/leadream/juuust-vue-icon/blob/2b6ee419db216ae1887a776454172702ff962a0e/.github/workflows/push.yml#L35
