### ISSUE TITLE
the stroke width in svg is 2 times of pic in fimga

### ISSUE THREAD

**Issue by jane-rose** [leadream/figma-icon-automation#7]
The svg graph is larger than the graph derived from figma, and the stroke width is 2 times of the fimga.

![image](https://user-images.githubusercontent.com/33253363/87421129-05a62000-c609-11ea-9297-0b8237425ebf.png)

![image](https://user-images.githubusercontent.com/33253363/87420946-c546a200-c608-11ea-8209-b1829c321852.png)

**Comment by leadream** [comment]
@jiantaolovebingbing I don't know what stack are you using now so I assume it's react. It's defined [here](https://github.com/leadream/juuust-icon/blob/master/bin/template.js#L15) so you can change the stroke in your own repo.

**Comment by yingdi-cheng** [comment]
我在figma设计这个图标时，粗细设置的是1px，想最后呈现时也是1px，但通过插件实现在页面上后，图标的粗细变成了2px,变成了原图2倍，效果图类似于上面的两个图标的对比图。因此想问一下是我们这边实现有哪些问题，还是哪里需要调整的，谢谢~

**Comment by leadream** [comment]
@yingdi-cheng 你可以改一下自己图标仓库的代码，我的示例仓库中代码位置如下：
React：https://github.com/leadream/juuust-icon/blob/master/bin/template.js#L15
Vue：https://github.com/leadream/juuust-vue-icon/blob/master/bin/template.js#L16
